server:
  port: 8081
  
spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**
ribbon:
  ConnectTimeout: 100
  ReadTimeout: 600
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000